#ifndef BLU2USB_FORK_BT_RUNTIME_H
#define BLU2USB_FORK_BT_RUNTIME_H

#include <stdint.h>

#define BT_COMMAND_PING 1u
#define BT_COMMAND_CLASSIC_CANCEL 2u
#define BT_COMMAND_CLASSIC_RETRY 3u

#define BT_EVENT_STACK_WORKING 1u
#define BT_EVENT_COMMAND_ACK 2u
#define BT_EVENT_STACK_ERROR 3u
#define BT_EVENT_CLASSIC_SCANNING 10u
#define BT_EVENT_CLASSIC_BONDING 11u
#define BT_EVENT_CLASSIC_CONNECTING 12u
#define BT_EVENT_CLASSIC_READY 13u
#define BT_EVENT_CLASSIC_RETRYING 14u
#define BT_EVENT_CLASSIC_CANCELLED 15u
#define BT_EVENT_KEYBOARD_SNAPSHOT 20u

void bt_runtime_core1_main(void);

#endif
