#ifndef BLU2USB_FORK_UI_CONTROL_H
#define BLU2USB_FORK_UI_CONTROL_H

typedef enum {
    BLU2USB_CONTROL_JOY_UP = 0,
    BLU2USB_CONTROL_JOY_DOWN,
    BLU2USB_CONTROL_JOY_LEFT,
    BLU2USB_CONTROL_JOY_RIGHT,
    BLU2USB_CONTROL_JOY_PRESS,
    BLU2USB_CONTROL_KEY_A,
    BLU2USB_CONTROL_KEY_B,
    BLU2USB_CONTROL_KEY_X,
    BLU2USB_CONTROL_KEY_Y,
    BLU2USB_CONTROL_COUNT
} blu2usb_control_t;

#endif
