#include "ui_renderer.h"
#include <stdio.h>

static void clear_row(blu2usb_ui_frame_t *f,uint8_t r){if(f==NULL||r>=9u)return;for(uint8_t c=0;c<21u;++c){f->cells[r][c].character=' ';f->cells[r][c].tone=BLU2USB_UI_TONE_ACTIONABLE;}}
static void current_preserve_selection(blu2usb_ui_frame_t *f,uint8_t r){if(f==NULL||r>=9u)return;for(uint8_t c=0;c<21u;++c){if(f->cells[r][c].character==' '||f->cells[r][c].tone==BLU2USB_UI_TONE_EMPHASIZED)continue;f->cells[r][c].tone=BLU2USB_UI_TONE_CURRENT;}}
static bool success_feedback(blu2usb_screen_id_t s){return s==BLU2USB_SCREEN_MOUSE_SAVED||s==BLU2USB_SCREEN_KEYBOARD_SAVED||s==BLU2USB_SCREEN_COMPOSITE_SAVED||s==BLU2USB_SCREEN_PASSTHROUGH_APPLIED||s==BLU2USB_SCREEN_DEFAULT_APPLIED||s==BLU2USB_SCREEN_ESCAPE_APPLIED||s==BLU2USB_SCREEN_CUSTOM_APPLIED;}
static uint8_t active_profile_row(const blu2usb_ux_model_t *ux){if(ux==NULL||ux->screen!=BLU2USB_SCREEN_MOUSE_OPTIONS)return 0u;switch(ux->active_profile){case BLU2USB_MOUSE_PROFILE_PASSTHROUGH:return 2u;case BLU2USB_MOUSE_PROFILE_DEFAULT_REMAP:return 3u;case BLU2USB_MOUSE_PROFILE_ESCAPE_REMAP:return 4u;case BLU2USB_MOUSE_PROFILE_CUSTOM_REMAP:return 5u;default:return 0u;}}
static const char *profile_name(blu2usb_mouse_profile_kind_t p){switch(p){case BLU2USB_MOUSE_PROFILE_PASSTHROUGH:return "PASSTHROUGH";case BLU2USB_MOUSE_PROFILE_DEFAULT_REMAP:return "DEFAULT";case BLU2USB_MOUSE_PROFILE_ESCAPE_REMAP:return "ESCAPE";case BLU2USB_MOUSE_PROFILE_CUSTOM_REMAP:return "CUSTOM";default:return "PASSTHROUGH";}}
static const char *source_name(unsigned s){static const char *const n[5]={"LEFT","RIGHT","MIDDLE","FORWARD","BACKWARD"};return s<5u?n[s]:"LEFT";}
static const char *target_name(blu2usb_mouse_target_t t){static const char *const n[6]={"LEFT","RIGHT","MIDDLE","BACKWARD","FORWARD","ESCAPE"};return(unsigned)t<6u?n[t]:"LEFT";}
static void project_custom(const blu2usb_ux_model_t *ux,blu2usb_ui_frame_t *f,bool applied){const bool clean=ux->active_profile==BLU2USB_MOUSE_PROFILE_CUSTOM_REMAP&&!ux->custom_dirty;for(uint8_t s=0;s<5u;++s){const uint8_t r=(uint8_t)(s+1u);char text[22];(void)snprintf(text,sizeof(text),applied?"%s IS %s":" %s IS %s",source_name(s),target_name(ux->custom_targets[s]));clear_row(f,r);const blu2usb_ui_tone_t tone=applied?BLU2USB_UI_TONE_CURRENT:ux->selection==s?BLU2USB_UI_TONE_EMPHASIZED:clean?BLU2USB_UI_TONE_CURRENT:BLU2USB_UI_TONE_ACTIONABLE;(void)blu2usb_ui_frame_set_text(f,r,0,text,tone);}if(!applied&&clean)clear_row(f,8u);}
static void project_mouse_status(const blu2usb_ux_model_t *ux,blu2usb_ui_frame_t *f){char profile[22];clear_row(f,1u);(void)blu2usb_ui_frame_set_text(f,1u,0u,blu2usb_ux_mouse_connected()?"MOUSE CONNECTED":"MOUSE NOT CONNECTED",blu2usb_ux_mouse_connected()?BLU2USB_UI_TONE_CURRENT:BLU2USB_UI_TONE_STATIC);(void)snprintf(profile,sizeof(profile),"PROFILE: %s",profile_name(ux->active_profile));clear_row(f,2u);(void)blu2usb_ui_frame_set_text(f,2u,0u,profile,BLU2USB_UI_TONE_STATIC);}
void blu2usb_ui_enforce_applied_visual_contract(const blu2usb_ux_model_t *ux,blu2usb_ui_frame_t *f){if(ux==NULL||f==NULL)return;if(success_feedback(ux->screen)){const uint8_t end=f->hint_start_row<9u?f->hint_start_row:9u;for(uint8_t r=1u;r<end;++r)current_preserve_selection(f,r);}if(ux->screen==BLU2USB_SCREEN_MOUSE_STATUS)project_mouse_status(ux,f);if(ux->screen==BLU2USB_SCREEN_MOUSE_OPTIONS&&blu2usb_ux_mouse_connected())current_preserve_selection(f,1u);const uint8_t pr=active_profile_row(ux);if(pr!=0u)current_preserve_selection(f,pr);if(ux->screen==BLU2USB_SCREEN_EDIT_CUSTOM)project_custom(ux,f,false);else if(ux->screen==BLU2USB_SCREEN_CUSTOM_APPLIED)project_custom(ux,f,true);if(ux->screen>=BLU2USB_SCREEN_LEFT_WILL_BECOME&&ux->screen<=BLU2USB_SCREEN_BACKWARD_WILL_BECOME){const uint8_t cr=(uint8_t)(1u+(unsigned)ux->custom_targets[ux->custom_source]);current_preserve_selection(f,cr);}}
